version: '3'
services: 

  ####################################################
  # Prometheus
  # Listens on port 9090
  ####################################################
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: 999:999
    restart: unless-stopped
    network_mode: host # required to be able to scrape from scrapers on localhost
    pid: host
    volumes: 
      - ./prometheus/config/:/etc/prometheus
      - ./prometheus/data:/data/prometheus
    command: 
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/data/prometheus'

  ####################################################
  # Node exporter
  # Listens on port 9100 by default
  ####################################################
  node_exporter:  
    image: prom/node-exporter:latest
    container_name: node_exporter
    user: 998:998
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
      - '--collector.processes'
      - '--collector.systemd'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    network_mode: host  # required for full functionality
    pid: host           # required for full functionality
    volumes:
      - '/:/host:ro,rslave'

  ####################################################
  # Sensors Exporter
  # Listens on port 9255 by default
  ####################################################
  sensors_exporter:  
    image: epflsti/cluster.coreos.prometheus-sensors:latest
    container_name: sensors_exporter
    restart: unless-stopped
    user: 997:997
    ports:
      - 9255:9255
    command: 
      - '--path.rootfs=/hostfs'
    volumes:
      - '/:/hostfs:ro'

  ####################################################
  # GPU Exporter
  # Listens on port 9445 by default
  ####################################################
  gpu_exporter:
    image: mindprince/nvidia_gpu_prometheus_exporter:0.1
    container_name: gpu_exporter
    restart: unless-stopped
    user: 990:990
    #network_mode: host
    #pid: host
    #cap_add: 
    #  - SYS_ADMIN
    ports:
      - 9445:9445
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]    
    volumes: 
      - /usr/local/cuda/lib64/stubs/:/usr/cuda
    environment: 
      -  LD_LIBRARY_PATH=/usr/cuda/libnvidia-ml.so

  ####################################################
  # Docker Exporter
  # Listens on port 8080 by default --> map to 8082 on localhost
  ####################################################
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    #user: 984:984            # does not work even if cadvisor user is added to docker group (don't know why)
    privileged: true
    ports:
      - 8082:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped

  #####################################################
  # InfluxDB & Telegraf
  # Listens on port 8086 by default
  # User/DB: grafana, PW: swaggrafana-password
  #####################################################
  influxdb:
      image: influxdb:latest
      container_name: influxdb
      restart: unless-stopped
      user: 983:983
      volumes:
        # Mount for influxdb data directory and configuration
        - ./influxdb/data:/var/lib/influxdb2:rw
        - ./influxdb/config.yml:/etc/influxdb2/config.yml:ro
      ports:
        - "8086:8086"
  telegraf:
    image: telegraf:latest
    restart: unless-stopped
    container_name: telegraf
    user: 983:983
    #network_mode: host
    pid: host
    volumes:
      - ./influxdb/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs 


  #####################################################
  # Loki and Promtail
  # Loki listens on port 3100 by default
  # Both need to run as root (to have access to logs)
  #####################################################
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki/:/mnt/config
      #- ./loki/data/:/loki  # ?? why doesn't work ??
    command: -config.file=/mnt/config/loki_local-config.yml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    ports: 
    - "1514:1514"
    - "9080:9080"
    volumes:
      - ./loki/:/mnt/config
      - /var/log/:/var/log:ro
    command: -config.file=/mnt/config/promtail_config.yml
    depends_on:
      - loki
  

  #####################################################
  # Grafana
  # Listens on port 3000 by default
  #####################################################
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: 472:472
    network_mode: host
    pid: host
    volumes:
      - ./grafana/data/:/var/lib/grafana
    restart: unless-stopped
