{
 "title": "Leo's Grafana Home",
 "description": "Customized home dashboard with most important metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" }
  ]
 },
 "panels": [
  {
   "title": "Dell-Poweredge UPTIME",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Dell-Poweredge Temperatures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "sensor_lm_temperature_celsius", "legendFormat": "{{temptype}}" }
   ]
  },
  {
   "title": "Leo's Room Co2 Measurement",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"Co2 Sensirion 2\" and\r\n    r._field == \"value\"\r\n  )"
    }
   ]
  },
  {
   "title": "Co2 Level (Sensirion)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"Co2 Sensirion 2\" and\r\n    r._field == \"value\"\r\n  )"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Dell-Poweredge CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Nvidia 1050Ti GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "nvidia_gpu_temperature_celsius", "legendFormat": "gpu{{minor_number}}" }
   ]
  },
  {
   "title": "Leo's Room Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"dht22_temp_correct\" and\r\n    r._field == \"value\"\r\n  )"
    }
   ]
  },
  {
   "title": "Leo's Room Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"dht22_hum_correct\" and\r\n    r._field == \"value\"\r\n  )"
    }
   ]
  },
  {
   "title": "eCo2 Level (CCS811)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"eCo2 CCS811\" and\r\n    r._field == \"value\"\r\n  )"
    }
   ]
  },
  {
   "title": "TOC Levels (CCS811)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"ccs811_toc\" and\r\n    r._field == \"value\"\r\n  )"
    }
   ]
  },
  {
   "title": "Dell-Poweredge Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Dell-Poweredge Disk Space",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\", mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / \nnode_filesystem_size_bytes{instance=\"$node\",job=\"$job\", mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "root fs 256GB"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\", mountpoint=\"/mnt/cloud1\",fstype!=\"rootfs\"} * 100) / \nnode_filesystem_size_bytes{instance=\"$node\",job=\"$job\", mountpoint=\"/mnt/cloud1\",fstype!=\"rootfs\"})",
     "legendFormat": "cloud1 1TB"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\", mountpoint=\"/mnt/cloud2\",fstype!=\"rootfs\"} * 100) / \nnode_filesystem_size_bytes{instance=\"$node\",job=\"$job\", mountpoint=\"/mnt/cloud2\",fstype!=\"rootfs\"})",
     "legendFormat": "cloud2 6TB"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\", mountpoint=\"/mnt/cloud3_backup\",fstype!=\"rootfs\"} * 100) / \nnode_filesystem_size_bytes{instance=\"$node\",job=\"$job\", mountpoint=\"/mnt/cloud3_backup\",fstype!=\"rootfs\"})",
     "legendFormat": "cloud3 8TB"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\", mountpoint=\"/media/external_2/\",fstype!=\"rootfs\"} * 100) / \nnode_filesystem_size_bytes{instance=\"$node\",job=\"$job\", mountpoint=\"/media/external_2/\",fstype!=\"rootfs\"})",
     "legendFormat": "External 2TB"
    }
   ]
  }
 ]
}